name: Validate Sigma Rules

on: 
  push:
    branches-ignore: main 
    paths:
      - 'sigma/**.yml'
      - 'sigma/**.yaml'
  pull_request:
    branches: main 
    paths:
      - 'sigma/**.yml'
      - 'sigma/**yaml'
    workflow_dispatch:


jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v5

      - name: Update and Install Python3
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip
      
      - name: Install Sigma CLI 
        run: pip3 install sigma-cli

      - name: Validate rules 
        run: sigma check sigma 

      - name: Install Sigma CLI backends
        if: github.event_name == 'pull_request'
        run: sigma plugin install splunk

      - name: Test conversion
        if: github.event_name == 'pull_request'
        run: sigma convert -t splunk -p splunk_windows -f default sigma 

#      - name: Test that post-process script runs w/o exceptions
#        if: github.event_name == 'pull_request'
#        run: python3 scripts/post-process.py 
